export default {
  KEYLESS_WIDGET_INITIALISED: 'KEYLESS_WIDGET_INITIALISED',
  KEYLESS_WIDGET_CLOSED: 'KEYLESS_WIDGET_CLOSED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SIGN_TRANSACTION_SUCCESSFUL: 'SIGN_TRANSACTION_SUCCESSFUL',
  SIGN_TRANSACTION_FAILED: 'SIGN_TRANSACTION_FAILED',
  SIGN_AND_SEND_TRANSACTION_SUCCESSFUL: 'SIGN_AND_SEND_TRANSACTION_SUCCESSFUL',
  SIGN_AND_SEND_TRANSACTION_FAILED: 'SIGN_AND_SEND_TRANSACTION_FAILED'
};