export default {
  KEYLESS_WIDGET_INITIALISED: 'KEYLESS_WIDGET_INITIALISED',
  KEYLESS_WIDGET_CLOSED: 'KEYLESS_WIDGET_CLOSED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  TRANSACTION_SUCCESSFUL: 'TRANSACTION_SUCCESSFUL',
};
